package com.javen.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeeklypreferences<M extends BaseWeeklypreferences<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String wp_id) {
		set("wp_id", wp_id);
		return (M)this;
	}

	public java.lang.String getWpId() {
		return getStr("wp_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setOldPrice(java.math.BigDecimal oldPrice) {
		set("old_price", oldPrice);
		return (M)this;
	}

	public java.math.BigDecimal getOldPrice() {
		return get("old_price");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setInventory(java.lang.String inventory) {
		set("inventory", inventory);
		return (M)this;
	}

	public java.lang.String getInventory() {
		return getStr("inventory");
	}

	public M setImages(java.lang.String images) {
		set("images", images);
		return (M)this;
	}

	public java.lang.String getImages() {
		return getStr("images");
	}

	public M setBuy(java.lang.String buy) {
		set("buy", buy);
		return (M)this;
	}

	public java.lang.String getBuy() {
		return getStr("buy");
	}

}
